---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-vol01
  labels:
    app: myapp
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: web-pv-claim
  capacity:
    storage: 1Gi
  hostPath:
    path: "/var/lib/data/vol01"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-vol02
  labels:
    app: myapp
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: mysql-pv-claim
  capacity:
    storage: 1Gi
  hostPath:
    path: "/var/lib/data/vol02"
