apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: myclaim
  hostPath:
   path: "/mnt/data/myapp/vol01"
